var lularoeColors = ['yellow', 'orange', 'pink', 'fuchsia', 'purple', 'blue', 'green', 'grey'],
    styleData = {
        'joy': {'price': 60, 'sizes': ['xs', 's', 'm', 'l', 'xl']},
        'tween': {'price': 23},
        'tall_&_curvy': {'price': 25},
        'kids_s/m': {'price': 23},
        'sloan': {'price': 28, 'sizes': [2, 4, 6, 8, 10, 12, 14]},
        'sarah': {'price': 70, 'sizes': ['xs', 's', 'm', 'l', 'xl']},
        'randy': {'price': 35, 'sizes': ['xxs', 'xs', 's', 'm', 'l', 'xl', '2xl', '3xl']},
        'perfect_t': {'price': 36, 'sizes': ['xxs', 'xs', 's', 'm', 'l', 'xl', '2xl', '3xl']},
        'patrick': {'price': 40, 'sizes': ['m', 'l', 'xl', '2xl', '3xl']},
        'one_size': {'price': 25},
        'nicole': {'price': 48, 'sizes': ['xxs', 'xs', 's', 'm', 'l', 'xl', '2xl', '3xl']},
        'monroe': {'price': 48, 'sizes': ['s', 'l']},
        'maxi': {'price': 42, 'sizes': ['xxs', 'xs', 's', 'm', 'l', 'xl', '2xl', '3xl']},
        'madison': {'price': 48, 'sizes': ['xs', 's', 'm', 'l', 'xl', '2xl', '3xl']},
        'kids_l/xl': {'price': 23},
        'lucy': {'price': 52, 'sizes': ['xxs', 'xs', 's', 'm', 'l', 'xl', '2xl']},
        'lola': {'price': 48, 'sizes': ['xxs', 'xs', 's', 'm', 'l', 'xl', '2xl']},
        'lindsay': {'price': 48, 'sizes': ['s', 'm', 'l']},
        'kids_azure': {'price': 25, 'sizes': [2, 4, 6, 8, 10, 12, 14]},
        'julia': {'price': 45, 'sizes': ['xxs', 'xs', 's', 'm', 'l', 'xl', '2xl', '3xl']},
        'jordan': {'price': 65, 'sizes': ['xs', 's', 'm', 'l', 'xl', '2xl']},
        'jill': {'price': 55, 'sizes': ['xxs', 'xs', 's', 'm', 'l', 'xl', '2xl']},
        'jade': {'price': 55, 'sizes': ['xs', 's', 'm', 'l', 'xl', '2xl']},
        'irma': {'price': 35, 'sizes': ['xxs', 'xs', 's', 'm', 'l', 'xl', '2xl', '3xl']},
        'gracie': {'price': 28, 'sizes': [2, 4, 6, 8, 10, 12, 14]},
        'dotdotsmile': {'price': 36, 'sizes': [2, '3/4', '5/6', 7, '8/10', '12/14']},
        'classic_t': {'price': 35, 'sizes': ['xxs', 'xs', 's', 'm', 'l', 'xl', '2xl', '3xl']},
        'cassie': {'price': 35, 'sizes': ['xs', 's', 'm', 'l', 'xl', '2xl', '3xl']},
        'azure': {'price': 35, 'sizes': ['xs', 's', 'm', 'l', 'xl', '2xl', '3xl']},
        'ana': {'price': 60, 'sizes': ['xs', 's', 'm', 'l', 'xl', '2xl', '3xl']},
        'amelia': {'price': 65, 'sizes': ['xxs', 'xs', 's', 'm', 'l', 'xl', '2xl']}//,
        //carly: {price: , sizes: ['s', 'm', 'l']}
    };
